const router = require("express").Router()
const accountRouters = require("./account.router")
const dashboardRouters = require("./dashboard.router")
const categoryRouters = require("./category.router")
const tourRouters = require("./tour.router")
const orderRouters = require("./order.router")
const userRouters = require("./user.router")
const contactRouters = require("./contact.router")
const settingRouters = require("./setting.router")
const profileRouters = require("./profile.router")
const authMiddleware = require("../../middlewares/admin/auth.middleware")
router.use("/category",authMiddleware.verifyTokens,categoryRouters)
router.use('/account',authMiddleware.verifyTokens,accountRouters)
router.use('/dashboard',authMiddleware.verifyTokens,dashboardRouters)
router.use('/tour',authMiddleware.verifyTokens,tourRouters)
router.use('/order',authMiddleware.verifyTokens,orderRouters)
router.use('/user',authMiddleware.verifyTokens,userRouters)
router.use('/contact',authMiddleware.verifyTokens,contactRouters)
router.use('/setting',authMiddleware.verifyTokens,settingRouters)
router.use('/profile',authMiddleware.verifyTokens,profileRouters)
router.use(authMiddleware.verifyTokens,(req, res) => {
  res.status(404).render("admin/pages/error-404.pug", {
    pageTitle: "404"
  })
})
module.exports = router